version: '3.8' 
 
services: 
 
  mongo: 
    ongodb:
    image: mongo:latest 
    container_name: mongo-db 
    restart: always 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: lappis 
      MONGO_INITDB_ROOT_PASSWORD: lappis
      MONGO_INITDB_DATABASE: mongo_database 

ports:
- 27017:27017

  volumes:
            - /mongo-db:/data 
        networks:
            - network

aplicationPart: 
        image: app:final
        build:
            context: src
            dockerfile: dockerfile
        ports:
            - 8000:8000
        networks:
            - network



networks:
    network:
      driver: bridge